backend:
  name: git-gateway
  branch: cms

locale: "ja"

media_folder: static/img
public_folder: /img

collections:
  - name: "Community"
    format: "json"
    files:
      files:
        - label: "About Page"
      name: "about"
      file: assets/content/community.json"
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Intro, name: intro, widget: markdown }
        - label: Team
          name: team
          widget: list
          fields:
            - { label: Name, name: name, widget: string }
            - { label: Position, name: position, widget: string }
            - { label: Photo, name: photo, widget: image }
